const common = {
  app: {
    name: 'WMS',
    language: 'Language',
    english: 'English',
    french: 'French',
  },
  common: {
    dashboard: 'Dashboard',
    search: 'Search',
    profile: 'Profile',
    logout: 'Logout',
    workspace: 'Workspace',
    loading: 'Loading...',
  },
  nav: {
    general: 'General',
    administration: 'Administration',
    inventory: 'Inventory',
    workflow: 'Workflow',
    workspace: 'Workspace',
    warehouseInventory: 'Warehouse inventory',
    dashboard: 'Dashboard',
    predictionDashboard: 'Prediction dashboard',
    assistant: 'Assistant',
    users: 'Users',
    supportTickets: 'Support tickets',
    reclamations: 'Reclamations',
    warehouses: 'Warehouses',
    products: 'Products',
    orders: 'Orders',
    shipments: 'Shipments',
    movements: 'Movements',
    restockAlerts: 'Restock alerts',
    myOrders: 'My Orders',
    shipmentTracking: 'Shipment Tracking',
  },
  roles: {
    admin: 'Admin',
    manager: 'Manager',
    customer: 'Customer',
    technicien: 'Technicien',
  },
  auth: {
    warehouseOperations: 'Warehouse operations',
    loginHeroTitle: 'Sign in to a cleaner, faster workspace.',
    loginHeroDescription: 'Access orders, shipments, inventory, and approvals from a calm business interface built for daily work.',
    orderWorkflow: 'Order workflow',
    inventoryVisibility: 'Inventory visibility',
    roleBasedAccess: 'Role-based access',
    welcomeBack: 'Welcome back',
    signIn: 'Sign in',
    registered: 'Registered',
    registrationSuccess: 'Registration successful. Login to continue.',
    emailAddress: 'Email address',
    password: 'Password',
    authenticating: 'Authenticating...',
    login: 'Login',
    noAccount: 'No account yet?',
    register: 'Register',
    visitingFirst: 'Visiting first?',
    openLanding: 'Open the public landing page',
    openRegistration: 'Open registration',
    registerHeroTitle: 'Create your account and wait for approval.',
    registerHeroDescription: 'Anyone can register. New accounts stay pending until an admin approves and assigns the final role.',
    pendingReview: 'Pending review',
    adminApproval: 'Admin approval',
    profileAutofill: 'Profile autofill',
    joinWorkspace: 'Join the workspace',
    newAccount: 'New account',
    fullNameOptional: 'Full name (optional)',
    email: 'Email',
    phone: 'Phone',
    phoneEightDigits: 'Phone must contain exactly 8 digits.',
    address: 'Address',
    cin: 'CIN (8 digits)',
    minPassword: 'Minimum 8 characters',
    cityStreetNumber: 'City, street, number',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    exploreCompany: 'Want to explore the company first?',
    goLanding: 'Go to landing page',
  },
  statuses: {
    pending: 'Pending',
    inProgress: 'In progress',
    completed: 'Completed',
    inTransit: 'In transit',
  },
};

export default common;
