const common = {
  app: {
    name: 'WMS',
    language: 'Language',
    english: 'English',
    french: 'French',
  },
  common: {
    dashboard: 'Dashboard',
    search: 'Search',
    profile: 'Profile',
    logout: 'Logout',
    workspace: 'Workspace',
    loading: 'Loading...',
  },
  nav: {
    general: 'General',
    administration: 'Administration',
    inventory: 'Inventory',
    workflow: 'Workflow',
    workspace: 'Workspace',
    warehouseInventory: 'Warehouse inventory',
    dashboard: 'Dashboard',
    predictionDashboard: 'Prediction dashboard',
    assistant: 'Assistant',
    users: 'Users',
    supportTickets: 'Support tickets',
    reclamations: 'Reclamations',
    warehouses: 'Warehouses',
    products: 'Products',
    orders: 'Orders',
    shipments: 'Shipments',
    movements: 'Movements',
    restockAlerts: 'Restock alerts',
    myOrders: 'My Orders',
    shipmentTracking: 'Shipment Tracking',
  },
  roles: {
    admin: 'Admin',
    manager: 'Manager',
    customer: 'Customer',
    technicien: 'Technicien',
  },
  auth: {
    warehouseOperations: 'Warehouse operations',
    loginHeroTitle: 'Sign in to a cleaner, faster workspace.',
    loginHeroDescription: 'Access orders, shipments, inventory, and approvals from a calm business interface built for daily work.',
    orderWorkflow: 'Order workflow',
    inventoryVisibility: 'Inventory visibility',
    roleBasedAccess: 'Role-based access',
    welcomeBack: 'Welcome back',
    signIn: 'Sign in',
    registered: 'Registered',
    registrationSuccess: 'Registration successful. Login to continue.',
    emailAddress: 'Email address',
    password: 'Password',
    authenticating: 'Authenticating...',
    login: 'Login',
    noAccount: 'No account yet?',
    register: 'Register',
    visitingFirst: 'Visiting first?',
    openLanding: 'Open the public landing page',
    openRegistration: 'Open registration',
    registerHeroTitle: 'Create your account and wait for approval.',
    registerHeroDescription: 'Anyone can register. New accounts stay pending until an admin approves and assigns the final role.',
    pendingReview: 'Pending review',
    adminApproval: 'Admin approval',
    profileAutofill: 'Profile autofill',
    joinWorkspace: 'Join the workspace',
    newAccount: 'New account',
    fullNameOptional: 'Full name (optional)',
    email: 'Email',
    phone: 'Phone',
    phoneEightDigits: 'Phone must contain exactly 8 digits.',
    address: 'Address',
    cin: 'CIN (8 digits)',
    minPassword: 'Minimum 8 characters',
    cityStreetNumber: 'City, street, number',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    exploreCompany: 'Want to explore the company first?',
    goLanding: 'Go to landing page',
  },
  statuses: {
    pending: 'Pending',
    inProgress: 'In progress',
    completed: 'Completed',
    inTransit: 'In transit',
  },
  phrases: {
    "Admin's dashboard": "Admin's dashboard",
    'Global operational overview across inventory, warehouses, users, orders, shipments, and support.': 'Global operational overview across inventory, warehouses, users, orders, shipments, and support.',
    'Manager panel': 'Manager panel',
    'Orders and inbound shipments operations': 'Orders and inbound shipments operations',
    'Products': 'Products',
    'Create, update, and monitor catalog inventory.': 'Create, update, and monitor catalog inventory.',
    'Users': 'Users',
    'Manage users, assign roles, and review account details.': 'Manage users, assign roles, and review account details.',
    'Warehouses': 'Warehouses',
    'Manage warehouse records, blocs, and capacities.': 'Manage warehouse records, blocs, and capacities.',
    'Support tickets': 'Support tickets',
    'Review incidents raised by technicians and operational alerts.': 'Review incidents raised by technicians and operational alerts.',
    'Reclamations': 'Reclamations',
    'Review customer complaints and resolve them from the admin dashboard.': 'Review customer complaints and resolve them from the admin dashboard.',
    'Price planning': 'Price planning',
    'Olive oil forecast in TND per 1L bottle, scenario checks, and model status.': 'Olive oil forecast in TND per 1L bottle, scenario checks, and model status.',
    'My Profile': 'My Profile',
    'Update your personal and delivery information.': 'Update your personal and delivery information.',
    'My Orders': 'My Orders',
    'Shipment Tracking': 'Shipment Tracking',
    'Raise and track customer complaints.': 'Raise and track customer complaints.',
    'Technician tickets': 'Technician tickets',
    'Create incident tickets for machines, products, delays, or alerts.': 'Create incident tickets for machines, products, delays, or alerts.',
    'Total products': 'Total products',
    'Registered products in stock': 'Registered products in stock',
    'Registered products in platform': 'Registered products in platform',
    'Stock quantity': 'Stock quantity',
    'Total product units across blocs': 'Total product units across blocs',
    'Total stock': 'Total stock',
    'All product quantities combined': 'All product quantities combined',
    'Capacity usage': 'Capacity usage',
    'Occupied warehouse capacity': 'Occupied warehouse capacity',
    'Occupied storage capacity': 'Occupied storage capacity',
    'My open tickets': 'My open tickets',
    'Technician tickets still active': 'Technician tickets still active',
    'Low stock': 'Low stock',
    'Products at or below': 'Products at or below',
    'Warehouses': 'Warehouses',
    'storage blocks': 'storage blocks',
    'Customers': 'Customers',
    'Registered customer accounts': 'Registered customer accounts',
    'Orders': 'Orders',
    'approved': 'approved',
    'rejected': 'rejected',
    'Active issues': 'Active issues',
    'Open tickets and reclamations': 'Open tickets and reclamations',
    'Block Capacity Usage': 'Block Capacity Usage',
    'Warehouse Capacity Usage': 'Warehouse Capacity Usage',
    'Low Stock Products': 'Low Stock Products',
    'Order Status': 'Order Status',
    'Movement Types': 'Movement Types',
    'Shipment Status': 'Shipment Status',
    'Support & Reclamations': 'Support & Reclamations',
    'Recent Movements': 'Recent Movements',
    'No data yet.': 'No data yet.',
    'No warehouse capacity data yet.': 'No warehouse capacity data yet.',
    'occupied': 'occupied',
    'No products below the low-stock threshold.': 'No products below the low-stock threshold.',
    'No inventory movements recorded yet.': 'No inventory movements recorded yet.',
    'units': 'units',
    'External': 'External',
    'Pending': 'Pending',
    'Approved': 'Approved',
    'Rejected': 'Rejected',
    'Restock requested': 'Restock requested',
    'Completed': 'Completed',
    'Requested': 'Requested',
    'In transit': 'In transit',
    'Received': 'Received',
    'Open': 'Open',
    'In progress': 'In progress',
    'Resolved': 'Resolved',
    'Closed': 'Closed',
    'Stock in': 'Stock in',
    'Stock out': 'Stock out',
    'Transfer': 'Transfer',
    'Damage': 'Damage',
    'Restock': 'Restock',
    'Restock alert': 'Restock alert',
    'Shipment created': 'Shipment created',
    'Order approved': 'Order approved',
    'Manager overview': 'Manager overview',
    "Manager's Dashboard": "Manager's Dashboard",
    'Missing auth token. Please login again.': 'Missing auth token. Please login again.',
    'Loading dashboard...': 'Loading dashboard...',
    'No BI data available yet.': 'No BI data available yet.',
    'Loading profile...': 'Loading profile...',
    'Failed to load profile': 'Failed to load profile',
    'Back': 'Back',
    'My profile': 'My profile',
    'Profile snapshot': 'Profile snapshot',
    'Unnamed user': 'Unnamed user',
    'User ID': 'User ID',
    'Role': 'Role',
    'Phone': 'Phone',
    'Timeline': 'Timeline',
    'Member since': 'Member since',
    'Last updated': 'Last updated'
    ,'Logout': 'Logout',
    'Forecast chart': 'Forecast chart',
    'Price movement overview': 'Price movement overview',
    'Trend bars': 'Trend bars',
    'Relative values': 'Relative values',
    'Last week': 'Last week',
    'This week': 'This week',
    'Forecast': 'Forecast',
    'Target': 'Target',
    'Prediction dashboard': 'Prediction dashboard',
    'Human-readable 1L bottle price forecast for planning and simulations': 'Human-readable 1L bottle price forecast for planning and simulations',
    'Review the next estimated price per 1-liter bottle, compare it with the last observed value, and test what-if scenarios before making decisions.': 'Review the next estimated price per 1-liter bottle, compare it with the last observed value, and test what-if scenarios before making decisions.',
    'Status': 'Status',
    'Loading forecast...': 'Loading forecast...',
    'Forecast ready': 'Forecast ready',
    'Awaiting data': 'Awaiting data',
    'Fetches automatically after sign-in.': 'Fetches automatically after sign-in.',
    'Refresh forecast': 'Refresh forecast',
    'Predicted price': 'Predicted price',
    'Next period estimate per 1L bottle': 'Next period estimate per 1L bottle',
    'Previous price': 'Previous price',
    'Latest observed 1L bottle price': 'Latest observed 1L bottle price',
    'Difference': 'Difference',
    'Model version': 'Model version',
    'Current deployed model': 'Current deployed model',
    'Business insight': 'Business insight',
    'Trend indicator': 'Trend indicator',
    'Simulation inputs': 'Simulation inputs',
    'What-if scenario': 'What-if scenario',
    'Unit standard: one sales unit equals one 1-liter olive oil bottle. Model v1 still expects cost and revenue, so both are estimated internally instead of being entered as scenario inputs.': 'Unit standard: one sales unit equals one 1-liter olive oil bottle. Model v1 still expects cost and revenue, so both are estimated internally instead of being entered as scenario inputs.',
    'Estimated cost sent to model': 'Estimated cost sent to model',
    'Estimated revenue sent to model': 'Estimated revenue sent to model',
    'Model notes': 'Model notes',
    'How to read the result': 'How to read the result',
    'The forecast compares the current estimate with the latest known price, so the change is easy to scan at a glance.': 'The forecast compares the current estimate with the latest known price, so the change is easy to scan at a glance.',
    'Use the chart to see whether the 1L bottle price is moving upward, downward, or staying flat over the next period.': 'Use the chart to see whether the 1L bottle price is moving upward, downward, or staying flat over the next period.',
    'The page stays intentionally simple so managers and admins can read it quickly during planning sessions.': 'The page stays intentionally simple so managers and admins can read it quickly during planning sessions.',
    'Current trend': 'Current trend',
    'The model expects an upward move. Consider reviewing stock and procurement timing.': 'The model expects an upward move. Consider reviewing stock and procurement timing.',
    'The model expects a downward move. You can prepare discount or clearance scenarios.': 'The model expects a downward move. You can prepare discount or clearance scenarios.',
    'The forecast is stable. The price is likely to stay close to the current level.': 'The forecast is stable. The price is likely to stay close to the current level.',
    'Please sign in to load predictions.': 'Please sign in to load predictions.',
    'Failed to load prediction data': 'Failed to load prediction data',
    'Updated at': 'Updated at',
    'forecast with': 'forecast with',
    'change': 'change',
    'year': 'year',
    'month': 'month',
    'stock': 'stock',
    'quantity sold': 'quantity sold'
    ,'Technician': 'Technician',
    'Review product stock and move inventory between blocs.': 'Review product stock and move inventory between blocs.',
    'Track and process restock alerts in one focused queue.': 'Track and process restock alerts in one focused queue.',
    'Track warehouse levels and real inventory movements in a live operational view.': 'Track warehouse levels and real inventory movements in a live operational view.',
    'Warehouse levels': 'Warehouse levels',
    'Read-only capacity overview for warehouses and blocs.': 'Read-only capacity overview for warehouses and blocs.',
    'Report issue': 'Report issue',
    'Loading warehouse levels...': 'Loading warehouse levels...',
    'No description': 'No description',
    'Surface': 'Surface',
    'Bloc': 'Bloc',
    'Capacity': 'Capacity',
    'Usage': 'Usage',
    'Available': 'Available',
    'Real-time flow': 'Real-time flow',
    'Latest movement': 'Latest movement',
    'Synced': 'Synced',
    'Qty': 'Qty',
    'Order': 'Order',
    'Shipment': 'Shipment',
    'Responsible': 'Responsible',
    'Unknown': 'Unknown',
    'No inventory movements yet.': 'No inventory movements yet.',
    'Transfers': 'Transfers',
    'Last synced': 'Last synced',
    'Low stock alerts': 'Low stock alerts',
    'High usage blocs': 'High usage blocs',
    'Unknown warehouse': 'Unknown warehouse',
    'No high usage blocs right now.': 'No high usage blocs right now.',
    'Warehouse inventory': 'Warehouse inventory',
    'Move product': 'Move product',
    'Product': 'Product',
    'Price': 'Price',
    'Warehouse': 'Warehouse',
    'No products in warehouse.': 'No products in warehouse.',
    'Technician alerts': 'Technician alerts',
    'Restock Alerts': 'Restock Alerts',
    'Live queue': 'Live queue',
    'Requested quantity': 'Requested quantity',
    'Priority': 'Priority',
    'Manager note': 'Manager note',
    'No note provided.': 'No note provided.',
    'Mark completed': 'Mark completed',
    'No restock alerts yet.': 'No restock alerts yet.',
    'Movement history': 'Movement history',
    'Real inventory operations': 'Real inventory operations',
    'Database-backed': 'Database-backed',
    'Source bloc': 'Source bloc',
    'Destination': 'Destination',
    'Operation': 'Operation',
    'Timestamp': 'Timestamp',
    'No operations recorded yet.': 'No operations recorded yet.',
    'Move product between blocs': 'Move product between blocs',
    'Close': 'Close',
    'Select product': 'Select product',
    'available in': 'available in',
    'Quantity': 'Quantity',
    'Select destination bloc': 'Select destination bloc',
    'Optional note': 'Optional note',
    'Moving product...': 'Moving product...',
    'Execute move': 'Execute move',
    'Damaged items': 'Damaged items',
    'Manage blocs included in this warehouse': 'Manage blocs included in this warehouse',
    'Customer Workspace': 'Customer Workspace',
    'Browse products, place requests, and track order progress.': 'Browse products, place requests, and track order progress.',
    'Track your orders and shipments in real-time.': 'Track your orders and shipments in real-time.',
    'Review capacity and bloc allocation in a clean operational view.': 'Review capacity and bloc allocation in a clean operational view.',
    'Track inbound flow and receive inventory with minimal friction.': 'Track inbound flow and receive inventory with minimal friction.',
    'Create, update, and remove products with the same operational controls as admin.': 'Create, update, and remove products with the same operational controls as admin.',
    'Track technician incidents and operational alerts.': 'Track technician incidents and operational alerts.',
    'Track customer orders and send restock alerts when stock is low.': 'Track customer orders and send restock alerts when stock is low.',
    'Users table is hidden': 'Users table is hidden',
    'Loading users...': 'Loading users...',
    'Loading products...': 'Loading products...',
    'Loading warehouses...': 'Loading warehouses...',
    'Loading blocs...': 'Loading blocs...',
    'Loading reclamations...': 'Loading reclamations...',
    'Loading tickets...': 'Loading tickets...',
    'Loading orders...': 'Loading orders...',
    'Loading shipments...': 'Loading shipments...',
    'EMAIL': 'EMAIL',
    'NAME': 'NAME',
    'ROLE': 'ROLE',
    'MORE': 'MORE',
    'DELETE': 'DELETE',
    'DESCRIPTION': 'DESCRIPTION',
    'BLOC ID': 'BLOC ID',
    'PRICE': 'PRICE',
    'QUANTITY': 'QUANTITY',
    'UPDATE': 'UPDATE',
    'WAREHOUSE': 'WAREHOUSE',
    'BLOC': 'BLOC',
    'CAPACITY': 'CAPACITY',
    'CURRENT USAGE': 'CURRENT USAGE',
    'AVAILABLE': 'AVAILABLE',
    'WAREHOUSE ID': 'WAREHOUSE ID',
    'UPDATED AT': 'UPDATED AT',
    'VIEW PRODUCTS': 'VIEW PRODUCTS',
    'TITLE': 'TITLE',
    'CATEGORY': 'CATEGORY',
    'PRIORITY': 'PRIORITY',
    'STATUS': 'STATUS',
    'CREATED BY': 'CREATED BY',
    'NOTE': 'NOTE',
    'ACTIONS': 'ACTIONS',
    'PRODUCT': 'PRODUCT',
    'ORDER': 'ORDER',
    'ETA / DELIVERY': 'ETA / DELIVERY',
    'No role / pending': 'No role / pending',
    'User details': 'User details',
    'Address:': 'Address:',
    'Phone:': 'Phone:',
    'Delete user': 'Delete user',
    'DELETE PRODUCT': 'DELETE PRODUCT',
    'DELETE WAREHOUSE': 'DELETE WAREHOUSE',
    'DELETE BLOC': 'DELETE BLOC',
    'Warehouse details': 'Warehouse details',
    'Bloc products': 'Bloc products',
    'Are you sure you want to delete this bloc?': 'Are you sure you want to delete this bloc?',
    'Summary': 'Summary',
    'Final status': 'Final status',
    'Description': 'Description',
    'Attachment': 'Attachment',
    'Final action': 'Final action',
    'Add context or resolution details': 'Add context or resolution details',
    'Manager note': 'Manager note',
    'Account status': 'Account status',
    'Role verification pending': 'Role verification pending',
    'Assistant': 'Assistant',
    'Warehouse Copilot': 'Warehouse Copilot',
    'Ask in plain language. Get instant operations answers.': 'Ask in plain language. Get instant operations answers.',
    'Live chat': 'Live chat',
    'Conversation': 'Conversation',
    'Product': 'Product',
    'Location': 'Location',
    'Ask stock, location, low stock, or order status...': 'Ask stock, location, low stock, or order status...',
    'Warehouse overview': 'Warehouse overview',
    'View warehouse details and bloc capacities.': 'View warehouse details and bloc capacities.',
    'Sort: Name': 'Sort: Name',
    'Sort: Surface': 'Sort: Surface',
    'Sort: Bloc count': 'Sort: Bloc count',
    'Bloc count': 'Bloc count',
    'Blocs': 'Blocs',
    'Shipment workflow': 'Shipment workflow',
    'Move shipments from Requested to In Transit and close them as Delivered.': 'Move shipments from Requested to In Transit and close them as Delivered.',
    'Filter: All statuses': 'Filter: All statuses',
    'Filter: Requested': 'Filter: Requested',
    'Filter: In Transit': 'Filter: In Transit',
    'Filter: Delivered': 'Filter: Delivered',
    'Delivered quantity': 'Delivered quantity',
    'Tracking number': 'Tracking number',
    'Delivery note': 'Delivery note',
    'Inventory action': 'Inventory action',
    'Send a restock alert': 'Send a restock alert',
    'Restock alert': 'Restock alert',
    'Send to technicien': 'Send to technicien',
    'Select a product': 'Select a product',
    'Enter quantity': 'Enter quantity',
    'Select a warehouse': 'Select a warehouse',
    'Select a bloc': 'Select a bloc',
    'Low': 'Low',
    'Medium': 'Medium',
    'High': 'High',
    'Current stock': 'Current stock',
    'Selected product': 'Selected product',
    'Note': 'Note',
    'Optional message for the technicien team': 'Optional message for the technicien team',
    'Order workflow': 'Order workflow',
    'Manage approvals, restock requests, and shipment handoff with a lightweight view.': 'Manage approvals, restock requests, and shipment handoff with a lightweight view.',
    'Filter: All statuses': 'Filter: All statuses',
    'Filter: Pending': 'Filter: Pending',
    'Filter: Approved': 'Filter: Approved',
    'Filter: Rejected': 'Filter: Rejected',
    'Sort: Latest': 'Sort: Latest',
    'Sort: Deadline': 'Sort: Deadline',
    'Sort: Quantity': 'Sort: Quantity',
    'Restock request': 'Restock request',
    'Requested': 'Requested',
    'Restock alert form': 'Restock alert form',
    'Target warehouse': 'Target warehouse',
    'Target bloc': 'Target bloc',
    'Low priority': 'Low priority',
    'Medium priority': 'Medium priority',
    'High priority': 'High priority',
    'Optional note for the technician': 'Optional note for the technician',
    'Deadline': 'Deadline',
    'Customer': 'Customer',
    'Actions': 'Actions',
    'Reject reason': 'Reject reason',
    'Manager note (optional)': 'Manager note (optional)',
    'No orders': 'No orders',
    'No scheduled orders in this filter.': 'No scheduled orders in this filter.',
    'Change': 'Change',
    'Previous': 'Previous',
    'Latest 1L bottle price': 'Latest 1L bottle price',
    'Model': 'Model',
    'Planning note': 'Planning note',
    'Test a business case': 'Test a business case',
    'No reclamations yet': 'No reclamations yet',
    'Problem Type': 'Problem Type',
    'Related Order': 'Related Order',
    'Related Shipment': 'Related Shipment',
    'Manager Note': 'Manager Note',
    'New Reclamation': 'New Reclamation',
    'Product Issue': 'Product Issue',
    'Shipment Issue': 'Shipment Issue',
    'Order Issue': 'Order Issue',
    'Describe the issue in detail...': 'Describe the issue in detail...',
    'Attachment (optional)': 'Attachment (optional)'
    ,'Overview': 'Overview',
    'New order': 'New order',
    'Dismiss': 'Dismiss',
    'has been delivered.': 'has been delivered.',
    'Failed to load customer dashboard': 'Failed to load customer dashboard',
    'Add at least one valid product.': 'Add at least one valid product.',
    'Phone number must contain exactly 8 digits.': 'Phone number must contain exactly 8 digits.',
    'Choose a valid delivery date.': 'Choose a valid delivery date.',
    'Delivery must be scheduled at least 10 days in advance.': 'Delivery must be scheduled at least 10 days in advance.',
    'We could not create your order. Please review your request and try again.': 'We could not create your order. Please review your request and try again.',
    'One or more selected products cannot be fulfilled right now. Please refresh the product list and try again.': 'One or more selected products cannot be fulfilled right now. Please refresh the product list and try again.',
    'Click on a product to place an order': 'Click on a product to place an order',
    'Click to order': 'Click to order',
    'No products match your search': 'No products match your search',
    'No products available right now': 'No products available right now',
    'My orders': 'My orders',
    'Track your order status in real time': 'Track your order status in real time',
    'QTY': 'QTY',
    'DELIVERY DATE': 'DELIVERY DATE',
    'SHIPMENT': 'SHIPMENT',
    'Delivered': 'Delivered',
    'No orders match your search': 'No orders match your search',
    'No orders yet': 'No orders yet',
    'Remove': 'Remove',
    'Add product': 'Add product',
    'Delivery date': 'Delivery date',
    'Delivery address': 'Delivery address',
    'Your name': 'Your name',
    'Your phone': 'Your phone',
    'Sending order...': 'Sending order...',
    'Fix delivery date first': 'Fix delivery date first',
    'Send order': 'Send order',
    'Availability is confirmed internally after submission.': 'Availability is confirmed internally after submission.',
    'Failed to fetch shipments': 'Failed to fetch shipments',
    'No shipments yet': 'No shipments yet',
    'Type': 'Type',
    'RESTOCK': 'RESTOCK',
    'ORDER': 'ORDER',
    'Tracking Number': 'Tracking Number',
    'Expected Delivery': 'Expected Delivery',
    'Received Date': 'Received Date',
    'Notes': 'Notes',
    'Created': 'Created',
    'Failed to fetch reclamations': 'Failed to fetch reclamations',
    'Failed to create reclamation': 'Failed to create reclamation',
    'Tracking': 'Tracking',
    'Selected attachment': 'Selected attachment',
    'Cancel': 'Cancel',
    'Submitting...': 'Submitting...',
    'Submit': 'Submit'
    ,'Customer panel': 'Customer panel',
    'Choose a product, submit an order request, and track its status': 'Choose a product, submit an order request, and track its status',
    'Available products': 'Available products',
    'View all': 'View all'
    ,'products': 'products',
    'Add new product': 'Add new product',
    'Update': 'Update',
    'Delete': 'Delete',
    'Deleting...': 'Deleting...',
    'No products found': 'No products found',
    'UPDATE PRODUCT': 'UPDATE PRODUCT',
    'ADD PRODUCT': 'ADD PRODUCT',
    'Edit': 'Edit',
    'Create a new product': 'Create a new product',
    'CANCEL': 'CANCEL',
    'SAVING...': 'SAVING...',
    'SAVE CHANGES': 'SAVE CHANGES',
    'CREATE PRODUCT': 'CREATE PRODUCT',
    'DELETING...': 'DELETING...',
    'Are you sure you want to delete this product?': 'Are you sure you want to delete this product?',
    'Choose the product, quantity, and destination bloc, then send a direct alert to the technicien team.': 'Choose the product, quantity, and destination bloc, then send a direct alert to the technicien team.',
    'Loading inventory data...': 'Loading inventory data...',
    'Fill in the product, requested quantity, and target bloc. The current stock comes from the selected product.': 'Fill in the product, requested quantity, and target bloc. The current stock comes from the selected product.',
    'Sending...': 'Sending...',
    'Send Restock Alert': 'Send Restock Alert',
    'Send restock alert': 'Send restock alert',
    'items': 'items',
    'Failed to update reclamation': 'Failed to update reclamation',
    'No reclamations found.': 'No reclamations found.',
    'Saved': 'Saved',
    'No manager note': 'No manager note',
    'Open attachment': 'Open attachment',
    'Not linked': 'Not linked',
    'Saving...': 'Saving...',
    'Save changes': 'Save changes',
    'visible shipments': 'visible shipments',
    'In Transit': 'In Transit',
    'usage': 'usage',
    'ETA': 'ETA',
    'Mark in transit': 'Mark in transit',
    'Mark delivered': 'Mark delivered',
    'Confirm delivery': 'Confirm delivery',
    'No shipments found': 'No shipments found',
    'table view': 'table view',
    'kanban view': 'kanban view',
    'calendar view': 'calendar view',
    'Limited stock': 'Limited stock',
    'Healthy': 'Healthy',
    'Unknown bloc': 'Unknown bloc',
    'Approve': 'Approve',
    'Reject': 'Reject',
    'Restock Request': 'Restock Request',
    'Confirm reject': 'Confirm reject',
    'No orders found': 'No orders found',
    'Failed to load support tickets': 'Failed to load support tickets',
    'Failed to create support ticket': 'Failed to create support ticket',
    'Failed to update ticket': 'Failed to update ticket',
    'Title and description are required.': 'Title and description are required.',
    'Ticket updated': 'Ticket updated',
    'Marked as': 'Marked as',
    'The issue is resolved.': 'The issue is resolved.',
    'The ticket is closed.': 'The ticket is closed.',
    'Dismiss notification': 'Dismiss notification',
    'tickets': 'tickets',
    'Title': 'Title',
    'Issue summary': 'Issue summary',
    'Category': 'Category',
    'Priority': 'Priority',
    'Machine malfunction': 'Machine malfunction',
    'Product issue': 'Product issue',
    'Delay': 'Delay',
    'Alert': 'Alert',
    'Critical': 'Critical',
    'Explain the malfunction, delay, alert, or product issue': 'Explain the malfunction, delay, alert, or product issue',
    'Creating ticket...': 'Creating ticket...',
    'Submit ticket': 'Submit ticket',
    'Mark resolved': 'Mark resolved',
    'Mark closed': 'Mark closed',
    'Ticket resolved': 'Ticket resolved',
    'No tickets found': 'No tickets found',
    'Could not load conversation history.': 'Could not load conversation history.',
    'Type a question first.': 'Type a question first.',
    'Assistant request failed': 'Assistant request failed',
    'Logged in as': 'Logged in as',
    'guest': 'guest',
    'History': 'History',
    'No previous conversation yet.': 'No previous conversation yet.',
    'Thinking...': 'Thinking...',
    'Send': 'Send',
    'Total units': 'Total units',
    'How much stock do we have for olive oil?': 'How much stock do we have for olive oil?',
    'Where is product B stored?': 'Where is product B stored?',
    'What is the status of order 123?': 'What is the status of order 123?',
    'Which items are almost out of stock?': 'Which items are almost out of stock?',
    'Hi. I can help with stock, locations, low-stock alerts, and order tracking.': 'Hi. I can help with stock, locations, low-stock alerts, and order tracking.',
    'Olive oil price forecast': 'Olive oil price forecast',
    'Next-period estimate for one 1-liter bottle, used for purchase timing, stock levels, and customer pricing.': 'Next-period estimate for one 1-liter bottle, used for purchase timing, stock levels, and customer pricing.',
    'per 1L bottle': 'per 1L bottle',
    'Waiting for forecast': 'Waiting for forecast',
    'Connect the inference service to see the next 1L bottle price estimate.': 'Connect the inference service to see the next 1L bottle price estimate.',
    'Price may rise': 'Price may rise',
    'A higher 1L bottle estimate can support earlier procurement or tighter stock allocation.': 'A higher 1L bottle estimate can support earlier procurement or tighter stock allocation.',
    'Price may soften': 'Price may soften',
    'A lower 1L bottle estimate can help with promotion planning or slower purchasing.': 'A lower 1L bottle estimate can help with promotion planning or slower purchasing.',
    'Price looks steady': 'Price looks steady',
    'The model does not show a strong move, so current pricing can stay under review.': 'The model does not show a strong move, so current pricing can stay under review.',
    'Scenario planner': 'Scenario planner',
    'Year': 'Year',
    'Month': 'Month',
    'Stock': 'Stock',
    'Quantity sold': 'Quantity sold',
    'Planning period': 'Planning period',
    '1 to 12': '1 to 12',
    'Available 1L bottles': 'Available 1L bottles',
    'Expected 1L bottles sold': 'Expected 1L bottles sold',
    'Refreshing...': 'Refreshing...',
    'Running scenario...': 'Running scenario...',
    'Run scenario': 'Run scenario',
    'Sign in as an admin or manager to load the forecast.': 'Sign in as an admin or manager to load the forecast.',
    'Forecast service is unavailable.': 'Forecast service is unavailable.',
    'Sign in as an admin or manager to run a scenario.': 'Sign in as an admin or manager to run a scenario.',
    'Prediction failed.': 'Prediction failed.',
    'Not available': 'Not available',
    'Not refreshed yet': 'Not refreshed yet',
    'vs previous': 'vs previous',
    'up': 'up',
    'down': 'down',
    'flat': 'flat'
  },
};

export default common;
