const common = {
  app: {
    name: 'WMS',
    language: 'Langue',
    english: 'Anglais',
    french: 'Francais',
  },
  common: {
    dashboard: 'Tableau de bord',
    search: 'Rechercher',
    profile: 'Profil',
    logout: 'Deconnexion',
    workspace: 'Espace de travail',
    loading: 'Chargement...',
  },
  nav: {
    general: 'General',
    administration: 'Administration',
    inventory: 'Inventaire',
    workflow: 'Flux de travail',
    workspace: 'Espace de travail',
    warehouseInventory: 'Inventaire entrepot',
    dashboard: 'Tableau de bord',
    predictionDashboard: 'Tableau de prediction',
    assistant: 'Assistant',
    users: 'Utilisateurs',
    supportTickets: 'Tickets support',
    reclamations: 'Reclamations',
    warehouses: 'Entrepots',
    products: 'Produits',
    orders: 'Commandes',
    shipments: 'Expeditions',
    movements: 'Mouvements',
    restockAlerts: 'Alertes de restockage',
    myOrders: 'Mes commandes',
    shipmentTracking: 'Suivi des expeditions',
  },
  roles: {
    admin: 'Admin',
    manager: 'Manager',
    customer: 'Client',
    technicien: 'Technicien',
  },
  auth: {
    warehouseOperations: 'Operations entrepot',
    loginHeroTitle: 'Connectez-vous a un espace de travail plus clair et plus rapide.',
    loginHeroDescription: 'Accedez aux commandes, expeditions, inventaire et validations depuis une interface professionnelle concue pour le travail quotidien.',
    orderWorkflow: 'Flux des commandes',
    inventoryVisibility: 'Visibilite inventaire',
    roleBasedAccess: 'Acces par role',
    welcomeBack: 'Bon retour',
    signIn: 'Connexion',
    registered: 'Inscrit',
    registrationSuccess: 'Inscription reussie. Connectez-vous pour continuer.',
    emailAddress: 'Adresse email',
    password: 'Mot de passe',
    authenticating: 'Authentification...',
    login: 'Se connecter',
    noAccount: 'Pas encore de compte ?',
    register: 'Creer un compte',
    visitingFirst: 'Premiere visite ?',
    openLanding: 'Ouvrir la page publique',
    openRegistration: 'Inscription ouverte',
    registerHeroTitle: 'Creez votre compte et attendez la validation.',
    registerHeroDescription: 'Tout le monde peut s inscrire. Les nouveaux comptes restent en attente jusqu a ce qu un admin valide et attribue le role final.',
    pendingReview: 'En attente',
    adminApproval: 'Validation admin',
    profileAutofill: 'Profil pre-rempli',
    joinWorkspace: 'Rejoindre l espace',
    newAccount: 'Nouveau compte',
    fullNameOptional: 'Nom complet (optionnel)',
    email: 'Email',
    phone: 'Telephone',
    phoneEightDigits: 'Le telephone doit contenir exactement 8 chiffres.',
    address: 'Adresse',
    cin: 'CIN (8 chiffres)',
    minPassword: 'Minimum 8 caracteres',
    cityStreetNumber: 'Ville, rue, numero',
    creatingAccount: 'Creation du compte...',
    alreadyHaveAccount: 'Vous avez deja un compte ?',
    exploreCompany: 'Vous voulez decouvrir la societe avant ?',
    goLanding: 'Aller a la page d accueil',
  },
  statuses: {
    pending: 'En attente',
    inProgress: 'En cours',
    completed: 'Termine',
    inTransit: 'En transit',
  },
};

export default common;
