const common = {
  app: {
    name: 'WMS',
    language: 'Langue',
    english: 'Anglais',
    french: 'Francais',
  },
  common: {
    dashboard: 'Tableau de bord',
    search: 'Rechercher',
    profile: 'Profil',
    logout: 'Deconnexion',
    workspace: 'Espace de travail',
    loading: 'Chargement...',
  },
  nav: {
    general: 'General',
    administration: 'Administration',
    inventory: 'Inventaire',
    workflow: 'Flux de travail',
    workspace: 'Espace de travail',
    warehouseInventory: 'Inventaire entrepot',
    dashboard: 'Tableau de bord',
    predictionDashboard: 'Tableau de prediction',
    assistant: 'Assistant',
    users: 'Utilisateurs',
    supportTickets: 'Tickets support',
    reclamations: 'Reclamations',
    warehouses: 'Entrepots',
    products: 'Produits',
    orders: 'Commandes',
    shipments: 'Expeditions',
    movements: 'Mouvements',
    restockAlerts: 'Alertes de restockage',
    myOrders: 'Mes commandes',
    shipmentTracking: 'Suivi des expeditions',
  },
  roles: {
    admin: 'Admin',
    manager: 'Manager',
    customer: 'Client',
    technicien: 'Technicien',
  },
  auth: {
    warehouseOperations: 'Operations entrepot',
    loginHeroTitle: 'Connectez-vous a un espace de travail plus clair et plus rapide.',
    loginHeroDescription: 'Accedez aux commandes, expeditions, inventaire et validations depuis une interface professionnelle concue pour le travail quotidien.',
    orderWorkflow: 'Flux des commandes',
    inventoryVisibility: 'Visibilite inventaire',
    roleBasedAccess: 'Acces par role',
    welcomeBack: 'Bon retour',
    signIn: 'Connexion',
    registered: 'Inscrit',
    registrationSuccess: 'Inscription reussie. Connectez-vous pour continuer.',
    emailAddress: 'Adresse email',
    password: 'Mot de passe',
    authenticating: 'Authentification...',
    login: 'Se connecter',
    noAccount: 'Pas encore de compte ?',
    register: 'Creer un compte',
    visitingFirst: 'Premiere visite ?',
    openLanding: 'Ouvrir la page publique',
    openRegistration: 'Inscription ouverte',
    registerHeroTitle: 'Creez votre compte et attendez la validation.',
    registerHeroDescription: 'Tout le monde peut s inscrire. Les nouveaux comptes restent en attente jusqu a ce qu un admin valide et attribue le role final.',
    pendingReview: 'En attente',
    adminApproval: 'Validation admin',
    profileAutofill: 'Profil pre-rempli',
    joinWorkspace: 'Rejoindre l espace',
    newAccount: 'Nouveau compte',
    fullNameOptional: 'Nom complet (optionnel)',
    email: 'Email',
    phone: 'Telephone',
    phoneEightDigits: 'Le telephone doit contenir exactement 8 chiffres.',
    address: 'Adresse',
    cin: 'CIN (8 chiffres)',
    minPassword: 'Minimum 8 caracteres',
    cityStreetNumber: 'Ville, rue, numero',
    creatingAccount: 'Creation du compte...',
    alreadyHaveAccount: 'Vous avez deja un compte ?',
    exploreCompany: 'Vous voulez decouvrir la societe avant ?',
    goLanding: 'Aller a la page d accueil',
  },
  statuses: {
    pending: 'En attente',
    inProgress: 'En cours',
    completed: 'Termine',
    inTransit: 'En transit',
  },
  phrases: {
    "Admin's dashboard": "Tableau de bord admin",
    'Global operational overview across inventory, warehouses, users, orders, shipments, and support.': 'Vue operationnelle globale de l inventaire, des entrepots, utilisateurs, commandes, expeditions et support.',
    'Manager panel': 'Espace manager',
    'Orders and inbound shipments operations': 'Operations des commandes et expeditions entrantes',
    'Products': 'Produits',
    'Create, update, and monitor catalog inventory.': 'Creez, modifiez et suivez l inventaire du catalogue.',
    'Users': 'Utilisateurs',
    'Manage users, assign roles, and review account details.': 'Gerez les utilisateurs, attribuez les roles et consultez les details des comptes.',
    'Warehouses': 'Entrepots',
    'Manage warehouse records, blocs, and capacities.': 'Gerez les entrepots, les blocs et les capacites.',
    'Support tickets': 'Tickets support',
    'Review incidents raised by technicians and operational alerts.': 'Consultez les incidents signales par les techniciens et les alertes operationnelles.',
    'Reclamations': 'Reclamations',
    'Review customer complaints and resolve them from the admin dashboard.': 'Consultez les reclamations clients et traitez-les depuis le tableau admin.',
    'Price planning': 'Planification des prix',
    'Olive oil forecast in TND per 1L bottle, scenario checks, and model status.': 'Prevision du prix de l huile d olive en TND par bouteille de 1L, scenarios et etat du modele.',
    'My Profile': 'Mon profil',
    'Update your personal and delivery information.': 'Mettez a jour vos informations personnelles et de livraison.',
    'My Orders': 'Mes commandes',
    'Shipment Tracking': 'Suivi des expeditions',
    'Raise and track customer complaints.': 'Creez et suivez les reclamations client.',
    'Technician tickets': 'Tickets technicien',
    'Create incident tickets for machines, products, delays, or alerts.': 'Creez des tickets pour les machines, produits, retards ou alertes.',
    'Total products': 'Total produits',
    'Registered products in stock': 'Produits enregistres en stock',
    'Registered products in platform': 'Produits enregistres sur la plateforme',
    'Stock quantity': 'Quantite en stock',
    'Total product units across blocs': 'Total des unites produit dans les blocs',
    'Total stock': 'Stock total',
    'All product quantities combined': 'Somme de toutes les quantites produit',
    'Capacity usage': 'Utilisation capacite',
    'Occupied warehouse capacity': 'Capacite entrepot occupee',
    'Occupied storage capacity': 'Capacite de stockage occupee',
    'My open tickets': 'Mes tickets ouverts',
    'Technician tickets still active': 'Tickets technicien encore actifs',
    'Low stock': 'Stock faible',
    'Products at or below': 'Produits au seuil ou sous',
    'storage blocks': 'blocs de stockage',
    'Customers': 'Clients',
    'Registered customer accounts': 'Comptes clients enregistres',
    'Orders': 'Commandes',
    'approved': 'approuvees',
    'rejected': 'rejetees',
    'Active issues': 'Problemes actifs',
    'Open tickets and reclamations': 'Tickets et reclamations ouverts',
    'Block Capacity Usage': 'Utilisation capacite des blocs',
    'Warehouse Capacity Usage': 'Utilisation capacite entrepots',
    'Low Stock Products': 'Produits en stock faible',
    'Order Status': 'Statut des commandes',
    'Movement Types': 'Types de mouvements',
    'Shipment Status': 'Statut des expeditions',
    'Support & Reclamations': 'Support et reclamations',
    'Recent Movements': 'Mouvements recents',
    'No data yet.': 'Aucune donnee pour le moment.',
    'No warehouse capacity data yet.': 'Aucune donnee de capacite entrepot pour le moment.',
    'occupied': 'occupe',
    'No products below the low-stock threshold.': 'Aucun produit sous le seuil de stock faible.',
    'No inventory movements recorded yet.': 'Aucun mouvement d inventaire enregistre.',
    'units': 'unites',
    'External': 'Externe',
    'Pending': 'En attente',
    'Approved': 'Approuve',
    'Rejected': 'Rejete',
    'Restock requested': 'Restockage demande',
    'Completed': 'Termine',
    'Requested': 'Demande',
    'In transit': 'En transit',
    'Received': 'Recu',
    'Open': 'Ouvert',
    'In progress': 'En cours',
    'Resolved': 'Resolu',
    'Closed': 'Ferme',
    'Stock in': 'Entree stock',
    'Stock out': 'Sortie stock',
    'Transfer': 'Transfert',
    'Damage': 'Dommage',
    'Restock': 'Restockage',
    'Restock alert': 'Alerte restockage',
    'Shipment created': 'Expedition creee',
    'Order approved': 'Commande approuvee',
    'Manager overview': 'Vue manager',
    "Manager's Dashboard": "Tableau de bord manager",
    'Missing auth token. Please login again.': 'Token manquant. Veuillez vous reconnecter.',
    'Loading dashboard...': 'Chargement du tableau de bord...',
    'No BI data available yet.': 'Aucune donnee BI disponible pour le moment.',
    'Loading profile...': 'Chargement du profil...',
    'Failed to load profile': 'Impossible de charger le profil',
    'Back': 'Retour',
    'My profile': 'Mon profil',
    'Profile snapshot': 'Apercu du profil',
    'Unnamed user': 'Utilisateur sans nom',
    'User ID': 'ID utilisateur',
    'Role': 'Role',
    'Phone': 'Telephone',
    'Timeline': 'Historique',
    'Member since': 'Membre depuis',
    'Last updated': 'Derniere mise a jour',
    'Logout': 'Deconnexion',
    'Forecast chart': 'Graphique previsionnel',
    'Price movement overview': 'Vue de l evolution du prix',
    'Trend bars': 'Barres de tendance',
    'Relative values': 'Valeurs relatives',
    'Last week': 'Semaine derniere',
    'This week': 'Cette semaine',
    'Forecast': 'Prevision',
    'Target': 'Objectif',
    'Prediction dashboard': 'Tableau de prediction',
    'Human-readable 1L bottle price forecast for planning and simulations': 'Prevision lisible du prix de la bouteille 1L pour la planification et les simulations',
    'Review the next estimated price per 1-liter bottle, compare it with the last observed value, and test what-if scenarios before making decisions.': 'Consultez le prochain prix estime par bouteille de 1 litre, comparez-le avec la derniere valeur observee et testez des scenarios avant decision.',
    'Status': 'Statut',
    'Loading forecast...': 'Chargement de la prevision...',
    'Forecast ready': 'Prevision prete',
    'Awaiting data': 'En attente des donnees',
    'Fetches automatically after sign-in.': 'Chargement automatique apres connexion.',
    'Refresh forecast': 'Actualiser la prevision',
    'Predicted price': 'Prix predit',
    'Next period estimate per 1L bottle': 'Estimation prochaine periode par bouteille 1L',
    'Previous price': 'Prix precedent',
    'Latest observed 1L bottle price': 'Dernier prix observe pour bouteille 1L',
    'Difference': 'Difference',
    'Model version': 'Version du modele',
    'Current deployed model': 'Modele actuellement deploye',
    'Business insight': 'Analyse metier',
    'Trend indicator': 'Indicateur de tendance',
    'Simulation inputs': 'Parametres de simulation',
    'What-if scenario': 'Scenario hypothese',
    'Unit standard: one sales unit equals one 1-liter olive oil bottle. Model v1 still expects cost and revenue, so both are estimated internally instead of being entered as scenario inputs.': 'Unite standard : une unite de vente correspond a une bouteille d huile d olive de 1 litre. Le modele v1 attend encore le cout et le revenu, donc ils sont estimes en interne au lieu d etre saisis.',
    'Estimated cost sent to model': 'Cout estime envoye au modele',
    'Estimated revenue sent to model': 'Revenu estime envoye au modele',
    'Model notes': 'Notes du modele',
    'How to read the result': 'Comment lire le resultat',
    'The forecast compares the current estimate with the latest known price, so the change is easy to scan at a glance.': 'La prevision compare l estimation actuelle avec le dernier prix connu afin de lire rapidement l evolution.',
    'Use the chart to see whether the 1L bottle price is moving upward, downward, or staying flat over the next period.': 'Utilisez le graphique pour voir si le prix de la bouteille 1L monte, baisse ou reste stable sur la prochaine periode.',
    'The page stays intentionally simple so managers and admins can read it quickly during planning sessions.': 'La page reste volontairement simple pour que managers et admins la lisent rapidement pendant la planification.',
    'Current trend': 'Tendance actuelle',
    'The model expects an upward move. Consider reviewing stock and procurement timing.': 'Le modele prevoit une hausse. Pensez a revoir le stock et le calendrier d approvisionnement.',
    'The model expects a downward move. You can prepare discount or clearance scenarios.': 'Le modele prevoit une baisse. Vous pouvez preparer des scenarios de remise ou de destockage.',
    'The forecast is stable. The price is likely to stay close to the current level.': 'La prevision est stable. Le prix devrait rester proche du niveau actuel.',
    'Please sign in to load predictions.': 'Veuillez vous connecter pour charger les predictions.',
    'Failed to load prediction data': 'Impossible de charger les donnees de prediction',
    'Updated at': 'Mis a jour le',
    'forecast with': 'prevision avec',
    'change': 'de variation',
    'year': 'annee',
    'month': 'mois',
    'stock': 'stock',
    'quantity sold': 'quantite vendue',
    'Technician': 'Technicien',
    'Review product stock and move inventory between blocs.': 'Consultez le stock produit et deplacez l inventaire entre les blocs.',
    'Track and process restock alerts in one focused queue.': 'Suivez et traitez les alertes de restockage dans une file claire.',
    'Track warehouse levels and real inventory movements in a live operational view.': 'Suivez les niveaux des entrepots et les mouvements reels dans une vue operationnelle en direct.',
    'Warehouse levels': 'Niveaux des entrepots',
    'Read-only capacity overview for warehouses and blocs.': 'Vue en lecture seule des capacites des entrepots et blocs.',
    'Report issue': 'Signaler un probleme',
    'Loading warehouse levels...': 'Chargement des niveaux entrepot...',
    'No description': 'Aucune description',
    'Surface': 'Surface',
    'Bloc': 'Bloc',
    'Capacity': 'Capacite',
    'Usage': 'Utilisation',
    'Available': 'Disponible',
    'Real-time flow': 'Flux temps reel',
    'Latest movement': 'Dernier mouvement',
    'Synced': 'Synchronise',
    'Qty': 'Qte',
    'Order': 'Commande',
    'Shipment': 'Expedition',
    'Responsible': 'Responsable',
    'Unknown': 'Inconnu',
    'No inventory movements yet.': 'Aucun mouvement d inventaire pour le moment.',
    'Transfers': 'Transferts',
    'Last synced': 'Derniere synchronisation',
    'Low stock alerts': 'Alertes stock faible',
    'High usage blocs': 'Blocs tres utilises',
    'Unknown warehouse': 'Entrepot inconnu',
    'No high usage blocs right now.': 'Aucun bloc tres utilise actuellement.',
    'Warehouse inventory': 'Inventaire entrepot',
    'Move product': 'Deplacer produit',
    'Product': 'Produit',
    'Price': 'Prix',
    'Warehouse': 'Entrepot',
    'No products in warehouse.': 'Aucun produit dans l entrepot.',
    'Technician alerts': 'Alertes technicien',
    'Restock Alerts': 'Alertes de restockage',
    'Live queue': 'File en direct',
    'Requested quantity': 'Quantite demandee',
    'Priority': 'Priorite',
    'Manager note': 'Note manager',
    'No note provided.': 'Aucune note fournie.',
    'Mark completed': 'Marquer termine',
    'No restock alerts yet.': 'Aucune alerte de restockage pour le moment.',
    'Movement history': 'Historique mouvements',
    'Real inventory operations': 'Operations inventaire reelles',
    'Database-backed': 'Base de donnees',
    'Source bloc': 'Bloc source',
    'Destination': 'Destination',
    'Operation': 'Operation',
    'Timestamp': 'Horodatage',
    'No operations recorded yet.': 'Aucune operation enregistree pour le moment.',
    'Move product between blocs': 'Deplacer un produit entre blocs',
    'Close': 'Fermer',
    'Select product': 'Selectionner un produit',
    'available in': 'disponible dans',
    'Quantity': 'Quantite',
    'Select destination bloc': 'Selectionner le bloc destination',
    'Optional note': 'Note optionnelle',
    'Moving product...': 'Deplacement du produit...',
    'Execute move': 'Executer le deplacement',
    'Damaged items': 'Articles endommages',
    'Manage blocs included in this warehouse': 'Gerez les blocs inclus dans cet entrepot',
    'Customer Workspace': 'Espace client',
    'Browse products, place requests, and track order progress.': 'Parcourez les produits, passez des demandes et suivez l avancement des commandes.',
    'Track your orders and shipments in real-time.': 'Suivez vos commandes et expeditions en temps reel.',
    'Review capacity and bloc allocation in a clean operational view.': 'Consultez la capacite et l allocation des blocs dans une vue operationnelle claire.',
    'Track inbound flow and receive inventory with minimal friction.': 'Suivez les flux entrants et receptionnez l inventaire simplement.',
    'Create, update, and remove products with the same operational controls as admin.': 'Creez, modifiez et supprimez les produits avec les memes controles operationnels que l admin.',
    'Track technician incidents and operational alerts.': 'Suivez les incidents technicien et les alertes operationnelles.',
    'Track customer orders and send restock alerts when stock is low.': 'Suivez les commandes client et envoyez des alertes de restockage quand le stock est faible.',
    'Users table is hidden': 'Le tableau utilisateurs est masque',
    'Loading users...': 'Chargement des utilisateurs...',
    'Loading products...': 'Chargement des produits...',
    'Loading warehouses...': 'Chargement des entrepots...',
    'Loading blocs...': 'Chargement des blocs...',
    'Loading reclamations...': 'Chargement des reclamations...',
    'Loading tickets...': 'Chargement des tickets...',
    'Loading orders...': 'Chargement des commandes...',
    'Loading shipments...': 'Chargement des expeditions...',
    'EMAIL': 'EMAIL',
    'NAME': 'NOM',
    'ROLE': 'ROLE',
    'MORE': 'PLUS',
    'DELETE': 'SUPPRIMER',
    'DESCRIPTION': 'DESCRIPTION',
    'BLOC ID': 'ID BLOC',
    'PRICE': 'PRIX',
    'QUANTITY': 'QUANTITE',
    'UPDATE': 'MODIFIER',
    'WAREHOUSE': 'ENTREPOT',
    'BLOC': 'BLOC',
    'CAPACITY': 'CAPACITE',
    'CURRENT USAGE': 'UTILISATION ACTUELLE',
    'AVAILABLE': 'DISPONIBLE',
    'WAREHOUSE ID': 'ID ENTREPOT',
    'UPDATED AT': 'MIS A JOUR',
    'VIEW PRODUCTS': 'VOIR PRODUITS',
    'TITLE': 'TITRE',
    'CATEGORY': 'CATEGORIE',
    'PRIORITY': 'PRIORITE',
    'STATUS': 'STATUT',
    'CREATED BY': 'CREE PAR',
    'NOTE': 'NOTE',
    'ACTIONS': 'ACTIONS',
    'PRODUCT': 'PRODUIT',
    'ORDER': 'COMMANDE',
    'ETA / DELIVERY': 'ETA / LIVRAISON',
    'No role / pending': 'Aucun role / en attente',
    'User details': 'Details utilisateur',
    'Address:': 'Adresse :',
    'Phone:': 'Telephone :',
    'Delete user': 'Supprimer utilisateur',
    'DELETE PRODUCT': 'SUPPRIMER PRODUIT',
    'DELETE WAREHOUSE': 'SUPPRIMER ENTREPOT',
    'DELETE BLOC': 'SUPPRIMER BLOC',
    'Warehouse details': 'Details entrepot',
    'Bloc products': 'Produits du bloc',
    'Are you sure you want to delete this bloc?': 'Voulez-vous vraiment supprimer ce bloc ?',
    'Summary': 'Resume',
    'Final status': 'Statut final',
    'Description': 'Description',
    'Attachment': 'Piece jointe',
    'Final action': 'Action finale',
    'Add context or resolution details': 'Ajoutez le contexte ou les details de resolution',
    'Account status': 'Statut du compte',
    'Role verification pending': 'Verification du role en attente',
    'Assistant': 'Assistant',
    'Warehouse Copilot': 'Copilote entrepot',
    'Ask in plain language. Get instant operations answers.': 'Posez vos questions simplement et obtenez des reponses operationnelles instantanees.',
    'Live chat': 'Chat en direct',
    'Conversation': 'Conversation',
    'Location': 'Emplacement',
    'Ask stock, location, low stock, or order status...': 'Demandez le stock, l emplacement, les alertes stock faible ou le statut commande...',
    'Warehouse overview': 'Vue entrepots',
    'View warehouse details and bloc capacities.': 'Consultez les details des entrepots et les capacites des blocs.',
    'Sort: Name': 'Tri : nom',
    'Sort: Surface': 'Tri : surface',
    'Sort: Bloc count': 'Tri : nombre de blocs',
    'Bloc count': 'Nombre de blocs',
    'Blocs': 'Blocs',
    'Shipment workflow': 'Flux expeditions',
    'Move shipments from Requested to In Transit and close them as Delivered.': 'Passez les expeditions de Demande a En transit puis fermez-les comme Livrees.',
    'Filter: All statuses': 'Filtre : tous les statuts',
    'Filter: Requested': 'Filtre : demande',
    'Filter: In Transit': 'Filtre : en transit',
    'Filter: Delivered': 'Filtre : livre',
    'Delivered quantity': 'Quantite livree',
    'Tracking number': 'Numero de suivi',
    'Delivery note': 'Note de livraison',
    'Inventory action': 'Action inventaire',
    'Send a restock alert': 'Envoyer une alerte de restockage',
    'Send to technicien': 'Envoyer au technicien',
    'Select a product': 'Selectionner un produit',
    'Enter quantity': 'Saisir la quantite',
    'Select a warehouse': 'Selectionner un entrepot',
    'Select a bloc': 'Selectionner un bloc',
    'Low': 'Faible',
    'Medium': 'Moyenne',
    'High': 'Haute',
    'Selected product': 'Produit selectionne',
    'Note': 'Note',
    'Optional message for the technicien team': 'Message optionnel pour l equipe technicien',
    'Order workflow': 'Flux commandes',
    'Manage approvals, restock requests, and shipment handoff with a lightweight view.': 'Gerez les validations, demandes de restockage et transferts expedition dans une vue simple.',
    'Filter: Pending': 'Filtre : en attente',
    'Filter: Approved': 'Filtre : approuve',
    'Filter: Rejected': 'Filtre : rejete',
    'Sort: Latest': 'Tri : recent',
    'Sort: Deadline': 'Tri : echeance',
    'Sort: Quantity': 'Tri : quantite',
    'Restock request': 'Demande de restockage',
    'Restock alert form': 'Formulaire alerte restockage',
    'Target warehouse': 'Entrepot cible',
    'Target bloc': 'Bloc cible',
    'Low priority': 'Priorite faible',
    'Medium priority': 'Priorite moyenne',
    'High priority': 'Priorite haute',
    'Optional note for the technician': 'Note optionnelle pour le technicien',
    'Deadline': 'Echeance',
    'Customer': 'Client',
    'Actions': 'Actions',
    'Reject reason': 'Motif du rejet',
    'Manager note (optional)': 'Note manager (optionnelle)',
    'No orders': 'Aucune commande',
    'No scheduled orders in this filter.': 'Aucune commande planifiee pour ce filtre.',
    'Change': 'Variation',
    'Previous': 'Precedent',
    'Latest 1L bottle price': 'Dernier prix bouteille 1L',
    'Model': 'Modele',
    'Planning note': 'Note de planification',
    'Test a business case': 'Tester un cas metier',
    'No reclamations yet': 'Aucune reclamation pour le moment',
    'Problem Type': 'Type de probleme',
    'Related Order': 'Commande liee',
    'Related Shipment': 'Expedition liee',
    'Manager Note': 'Note manager',
    'New Reclamation': 'Nouvelle reclamation',
    'Product Issue': 'Probleme produit',
    'Shipment Issue': 'Probleme expedition',
    'Order Issue': 'Probleme commande',
    'Describe the issue in detail...': 'Decrivez le probleme en detail...',
    'Attachment (optional)': 'Piece jointe (optionnelle)',
    'Overview': 'Apercu',
    'New order': 'Nouvelle commande',
    'Dismiss': 'Fermer',
    'has been delivered.': 'a ete livree.',
    'Failed to load customer dashboard': 'Impossible de charger l espace client',
    'Add at least one valid product.': 'Ajoutez au moins un produit valide.',
    'Phone number must contain exactly 8 digits.': 'Le numero de telephone doit contenir exactement 8 chiffres.',
    'Choose a valid delivery date.': 'Choisissez une date de livraison valide.',
    'Delivery must be scheduled at least 10 days in advance.': 'La livraison doit etre planifiee au moins 10 jours a l avance.',
    'We could not create your order. Please review your request and try again.': 'Nous n avons pas pu creer votre commande. Verifiez votre demande puis reessayez.',
    'One or more selected products cannot be fulfilled right now. Please refresh the product list and try again.': 'Un ou plusieurs produits selectionnes ne peuvent pas etre fournis actuellement. Actualisez la liste puis reessayez.',
    'Click on a product to place an order': 'Cliquez sur un produit pour passer une commande',
    'Click to order': 'Cliquer pour commander',
    'No products match your search': 'Aucun produit ne correspond a votre recherche',
    'No products available right now': 'Aucun produit disponible actuellement',
    'My orders': 'Mes commandes',
    'Track your order status in real time': 'Suivez le statut de vos commandes en temps reel',
    'QTY': 'QTE',
    'DELIVERY DATE': 'DATE LIVRAISON',
    'SHIPMENT': 'EXPEDITION',
    'Delivered': 'Livre',
    'No orders match your search': 'Aucune commande ne correspond a votre recherche',
    'No orders yet': 'Aucune commande pour le moment',
    'Remove': 'Retirer',
    'Add product': 'Ajouter produit',
    'Delivery date': 'Date de livraison',
    'Delivery address': 'Adresse de livraison',
    'Your name': 'Votre nom',
    'Your phone': 'Votre telephone',
    'Sending order...': 'Envoi de la commande...',
    'Fix delivery date first': 'Corrigez d abord la date de livraison',
    'Send order': 'Envoyer la commande',
    'Availability is confirmed internally after submission.': 'La disponibilite est confirmee en interne apres soumission.',
    'Failed to fetch shipments': 'Impossible de recuperer les expeditions',
    'No shipments yet': 'Aucune expedition pour le moment',
    'Type': 'Type',
    'RESTOCK': 'RESTOCKAGE',
    'ORDER': 'COMMANDE',
    'Tracking Number': 'Numero de suivi',
    'Expected Delivery': 'Livraison prevue',
    'Received Date': 'Date de reception',
    'Notes': 'Notes',
    'Created': 'Cree le',
    'Failed to fetch reclamations': 'Impossible de recuperer les reclamations',
    'Failed to create reclamation': 'Impossible de creer la reclamation',
    'Tracking': 'Suivi',
    'Selected attachment': 'Piece jointe selectionnee',
    'Cancel': 'Annuler',
    'Submitting...': 'Envoi...',
    'Submit': 'Soumettre',
    'Customer panel': 'Espace client',
    'Choose a product, submit an order request, and track its status': 'Choisissez un produit, envoyez une demande de commande et suivez son statut',
    'Available products': 'Produits disponibles',
    'View all': 'Voir tout',
    'products': 'produits',
    'Add new product': 'Ajouter produit',
    'Update': 'Modifier',
    'Delete': 'Supprimer',
    'Deleting...': 'Suppression...',
    'No products found': 'Aucun produit trouve',
    'UPDATE PRODUCT': 'MODIFIER PRODUIT',
    'ADD PRODUCT': 'AJOUTER PRODUIT',
    'Edit': 'Modifier',
    'Create a new product': 'Creer un nouveau produit',
    'CANCEL': 'ANNULER',
    'SAVING...': 'ENREGISTREMENT...',
    'SAVE CHANGES': 'ENREGISTRER',
    'CREATE PRODUCT': 'CREER PRODUIT',
    'DELETING...': 'SUPPRESSION...',
    'Are you sure you want to delete this product?': 'Voulez-vous vraiment supprimer ce produit ?',
    'Choose the product, quantity, and destination bloc, then send a direct alert to the technicien team.': 'Choisissez le produit, la quantite et le bloc destination, puis envoyez une alerte directe a l equipe technicien.',
    'Loading inventory data...': 'Chargement des donnees inventaire...',
    'Fill in the product, requested quantity, and target bloc. The current stock comes from the selected product.': 'Renseignez le produit, la quantite demandee et le bloc cible. Le stock actuel vient du produit selectionne.',
    'Sending...': 'Envoi...',
    'Send Restock Alert': 'Envoyer alerte restockage',
    'Send restock alert': 'Envoyer alerte restockage',
    'items': 'elements',
    'Failed to update reclamation': 'Impossible de mettre a jour la reclamation',
    'No reclamations found.': 'Aucune reclamation trouvee.',
    'Saved': 'Enregistre',
    'No manager note': 'Aucune note manager',
    'Open attachment': 'Ouvrir la piece jointe',
    'Not linked': 'Non lie',
    'Saving...': 'Enregistrement...',
    'Save changes': 'Enregistrer',
    'visible shipments': 'expeditions visibles',
    'In Transit': 'En transit',
    'usage': 'utilisation',
    'ETA': 'ETA',
    'Mark in transit': 'Marquer en transit',
    'Mark delivered': 'Marquer livre',
    'Confirm delivery': 'Confirmer livraison',
    'No shipments found': 'Aucune expedition trouvee',
    'table view': 'vue tableau',
    'kanban view': 'vue kanban',
    'calendar view': 'vue calendrier',
    'Limited stock': 'Stock limite',
    'Healthy': 'Correct',
    'Unknown bloc': 'Bloc inconnu',
    'Approve': 'Approuver',
    'Reject': 'Rejeter',
    'Restock Request': 'Demande restockage',
    'Confirm reject': 'Confirmer rejet',
    'No orders found': 'Aucune commande trouvee',
    'Failed to load support tickets': 'Impossible de charger les tickets support',
    'Failed to create support ticket': 'Impossible de creer le ticket support',
    'Failed to update ticket': 'Impossible de mettre a jour le ticket',
    'Title and description are required.': 'Le titre et la description sont obligatoires.',
    'Ticket updated': 'Ticket mis a jour',
    'Marked as': 'Marque comme',
    'The issue is resolved.': 'Le probleme est resolu.',
    'The ticket is closed.': 'Le ticket est ferme.',
    'Dismiss notification': 'Fermer la notification',
    'tickets': 'tickets',
    'Title': 'Titre',
    'Issue summary': 'Resume du probleme',
    'Category': 'Categorie',
    'Priority': 'Priorite',
    'Machine malfunction': 'Panne machine',
    'Product issue': 'Probleme produit',
    'Delay': 'Retard',
    'Alert': 'Alerte',
    'Critical': 'Critique',
    'Explain the malfunction, delay, alert, or product issue': 'Expliquez la panne, le retard, l alerte ou le probleme produit',
    'Creating ticket...': 'Creation du ticket...',
    'Submit ticket': 'Envoyer le ticket',
    'Mark resolved': 'Marquer resolu',
    'Mark closed': 'Marquer ferme',
    'Ticket resolved': 'Ticket resolu',
    'No tickets found': 'Aucun ticket trouve',
    'Could not load conversation history.': 'Impossible de charger l historique de conversation.',
    'Type a question first.': 'Saisissez d abord une question.',
    'Assistant request failed': 'La demande assistant a echoue',
    'Logged in as': 'Connecte en tant que',
    'guest': 'invite',
    'History': 'Historique',
    'No previous conversation yet.': 'Aucune conversation precedente.',
    'Thinking...': 'Reflexion...',
    'Send': 'Envoyer',
    'Total units': 'Total unites',
    'How much stock do we have for olive oil?': 'Combien de stock avons-nous pour l huile d olive ?',
    'Where is product B stored?': 'Ou est stocke le produit B ?',
    'What is the status of order 123?': 'Quel est le statut de la commande 123 ?',
    'Which items are almost out of stock?': 'Quels articles sont presque en rupture de stock ?',
    'Hi. I can help with stock, locations, low-stock alerts, and order tracking.': 'Bonjour. Je peux aider avec le stock, les emplacements, les alertes de stock faible et le suivi des commandes.',
    'Olive oil price forecast': 'Prevision du prix de l huile d olive',
    'Next-period estimate for one 1-liter bottle, used for purchase timing, stock levels, and customer pricing.': 'Estimation de la prochaine periode pour une bouteille de 1 litre, utile pour les achats, le stock et les prix client.',
    'per 1L bottle': 'par bouteille 1L',
    'Waiting for forecast': 'En attente de prevision',
    'Connect the inference service to see the next 1L bottle price estimate.': 'Connectez le service d inference pour voir la prochaine estimation du prix bouteille 1L.',
    'Price may rise': 'Le prix peut augmenter',
    'A higher 1L bottle estimate can support earlier procurement or tighter stock allocation.': 'Une estimation 1L plus elevee peut justifier des achats plus tot ou une allocation de stock plus stricte.',
    'Price may soften': 'Le prix peut baisser',
    'A lower 1L bottle estimate can help with promotion planning or slower purchasing.': 'Une estimation 1L plus basse peut aider a planifier les promotions ou ralentir les achats.',
    'Price looks steady': 'Le prix semble stable',
    'The model does not show a strong move, so current pricing can stay under review.': 'Le modele ne montre pas de forte variation, le prix actuel peut donc rester sous surveillance.',
    'Scenario planner': 'Planificateur de scenario',
    'Year': 'Annee',
    'Month': 'Mois',
    'Stock': 'Stock',
    'Quantity sold': 'Quantite vendue',
    'Planning period': 'Periode de planification',
    '1 to 12': '1 a 12',
    'Available 1L bottles': 'Bouteilles 1L disponibles',
    'Expected 1L bottles sold': 'Bouteilles 1L prevues vendues',
    'Refreshing...': 'Actualisation...',
    'Running scenario...': 'Execution du scenario...',
    'Run scenario': 'Executer le scenario',
    'Sign in as an admin or manager to load the forecast.': 'Connectez-vous comme admin ou manager pour charger la prevision.',
    'Forecast service is unavailable.': 'Le service de prevision est indisponible.',
    'Sign in as an admin or manager to run a scenario.': 'Connectez-vous comme admin ou manager pour executer un scenario.',
    'Prediction failed.': 'La prediction a echoue.',
    'Not available': 'Non disponible',
    'Not refreshed yet': 'Pas encore actualise',
    'Scenario result': 'Resultat du scenario',
    'Compared with current reference': 'Compare a la reference actuelle',
    'vs previous': 'vs precedent',
    'up': 'hausse',
    'down': 'baisse',
    'flat': 'stable',
    'Olive oil factory': 'Usine d huile d olive',
    'Login': 'Se connecter',
    'Contact us': 'Contactez-nous',
    'Our story': 'Notre histoire',
    'Tunisian heritage, crafted with care': 'Heritage tunisien, travaille avec soin',
    'A refined olive oil factory built on heritage, precision, and care.': 'Une usine d huile d olive raffinee, fondee sur l heritage, la precision et le soin.',
    'We bring together carefully selected Tunisian olives, disciplined production, elegant packaging, and a clear commitment to quality. The result is a factory story that feels premium, honest, and easy to trust.': 'Nous reunissons des olives tunisiennes soigneusement selectionnees, une production disciplinee, un packaging elegant et un engagement clair pour la qualite. Le resultat est une histoire d usine premium, sincere et facile a faire confiance.',
    'Learn about the factory': 'Decouvrir l usine',
    'Traceable batches': 'Lots tracables',
    'Inventory visibility': 'Visibilite inventaire',
    'Quality checkpoints': 'Points de controle qualite',
    'Factory story': 'Histoire de l usine',
    'Harvest selection': 'Selection de la recolte',
    'Only well-timed olives enter the process, protecting aroma and freshness from the start.': 'Seules les olives recoltees au bon moment entrent dans le processus, afin de proteger l arome et la fraicheur des le depart.',
    'Careful pressing': 'Pressage soigne',
    'The factory keeps pressing conditions controlled so the oil stays bright, clean, and expressive.': 'L usine controle les conditions de pressage pour garder une huile lumineuse, propre et expressive.',
    'Elegant packaging': 'Packaging elegant',
    'Final presentation is kept refined and export-ready, with attention to every label and bottle.': 'La presentation finale reste raffinee et prete pour l export, avec attention a chaque etiquette et bouteille.',
    'Factory at a glance': 'L usine en bref',
    'Quality you can see, heritage you can trust.': 'Une qualite visible, un heritage fiable.',
    'From harvest selection to packaging, each step is handled with care so the factory presents a premium, trustworthy identity to every visitor.': 'De la selection de la recolte au packaging, chaque etape est traitee avec soin pour presenter une identite premium et fiable a chaque visiteur.',
    'Authentic Tunisian sourcing': 'Origine tunisienne authentique',
    'Controlled production and storage': 'Production et stockage controles',
    'Export-ready packaging and traceability': 'Packaging et tracabilite prets pour l export',
    'The factory story': 'L histoire de l usine',
    'Built around care, not noise': 'Construite autour du soin, pas du bruit',
    'Tunisian sourcing': 'Approvisionnement tunisien',
    'We start with olives that reflect the character of the region and the rhythm of the harvest.': 'Nous commencons par des olives qui refletent le caractere de la region et le rythme de la recolte.',
    'Precision handling': 'Manipulation precise',
    'Storage, movement, and packaging are handled with discipline to preserve quality end to end.': 'Le stockage, les mouvements et le packaging sont geres avec discipline pour preserver la qualite de bout en bout.',
    'A clear identity': 'Une identite claire',
    'Everything the visitor sees should feel calm, premium, and rooted in the factory itself.': 'Tout ce que le visiteur voit doit etre calme, premium et ancre dans l usine elle-meme.',
    'Selected collections': 'Collections selectionnees',
    'A calm showcase of the range': 'Une presentation calme de la gamme',
    'Extra Virgin Reserve': 'Reserve extra vierge',
    'Cold pressed from selected Tunisian olives with a clean, balanced finish.': 'Pressee a froid a partir d olives tunisiennes selectionnees, avec une finale propre et equilibree.',
    'Organic Heritage Blend': 'Assemblage heritage bio',
    'A softer profile shaped for everyday tables, hospitality, and retail shelves.': 'Un profil plus doux, pense pour les tables du quotidien, l hotellerie et les rayons retail.',
    'Factory Signature Edition': 'Edition signature de l usine',
    'The flagship expression of our factory, prepared for export and gifting.': 'L expression phare de notre usine, preparee pour l export et les cadeaux.',
    '250ml / 500ml / 1L prepared with care': '250ml / 500ml / 1L prepares avec soin',
    'What defines us': 'Ce qui nous definit',
    'A premium public face': 'Une vitrine publique premium',
    'Tunisian olive heritage': 'Heritage oleicole tunisien',
    'Consistent quality checks': 'Controles qualite constants',
    'Careful storage and handling': 'Stockage et manipulation soignes',
    'Export-ready presentation': 'Presentation prete pour l export',
    'Sustainable operations': 'Operations durables',
    'A factory with a clear identity': 'Une usine avec une identite claire',
    'Presented with a calm, modern visual language that keeps the factory front and center.': 'Presente avec un langage visuel calme et moderne qui garde l usine au centre.',
    'Visit the factory': 'Visiter l usine',
    'A final invitation': 'Une derniere invitation',
    'Factory presence': 'Presence de l usine',
    'A cleaner, calmer, more credible first impression.': 'Une premiere impression plus claire, plus calme et plus credible.',
    'This page is meant to welcome visitors, show the identity of the factory, and communicate quality without overwhelming them with internal application details.': 'Cette page accueille les visiteurs, montre l identite de l usine et communique la qualite sans les submerger avec les details internes de l application.',
    'Quick links': 'Liens rapides',
    'Tell us what you need': 'Dites-nous ce dont vous avez besoin',
    'Close contact form': 'Fermer le formulaire de contact',
    'E-mail': 'E-mail',
    'Phone number': 'Numero de telephone',
    'Contact reason': 'Motif du contact',
    'General inquiry': 'Demande generale',
    'Product information': 'Information produit',
    'Wholesale request': 'Demande grossiste',
    'Other': 'Autre',
    'Send request': 'Envoyer la demande',
    'Request received': 'Demande recue',
    'We will contact you soon, thank you for your interest.': 'Nous vous contacterons bientot, merci pour votre interet.',
    'Sending request...': 'Envoi de la demande...',
    'Failed to send request': 'Impossible d envoyer la demande',
    'Failed to send contact request': 'Impossible d envoyer la demande de contact',
    'Public contact requests': 'Demandes de contact publiques',
    'No contact requests yet.': 'Aucune demande de contact pour le moment.',
    'new visitor inquiries need follow-up.': 'nouvelles demandes visiteur a traiter.',
    'Mark contacted': 'Marquer contacte',
    'Failed to update contact request': 'Impossible de mettre a jour la demande de contact',
    'Visitor inquiries': 'Demandes visiteurs',
    'New visitor inquiries': 'Nouvelles demandes visiteurs'
  },
};

export default common;
